version: '3.8'

services:
  Releasarr:
    image: Makario1337/Releasarr:latest
    ports:
      - "127.0.0.1:1337:1337"
    environment:
      APP_PORT: 1337
      APP_WORKERS: 4
    command: ["gunicorn", "app.main:app", "--bind", "0.0.0.0:${APP_PORT}", "--workers", "${APP_WORKERS}", "--worker-class", "uvicorn.workers.UvicornWorker"]